[technote]
id = "TESTN-135"
series_id = "TESTN"
canonical_url = "https://testn-135.lsst.io"
github_url = "https://github.com/lsst-sqre-testing/testn-135"
github_default_branch = "main"
date_created = 2024-09-25T15:27:57Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Jonathan"
name.family = "Sick"
internal_id = "sickj"
orcid = "https://orcid.org/0000-0003-3001-676X"
[[technote.authors.affiliations]]
name = "J.Sick Codes Inc."
internal_id = "JSickCodes"
address = "Penetanguishene, Ontario, Canada"
